version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - imagemagick

python:
  install:
    - method: pip
      path: .
    - method: pip
      pip_install:  # Directly install Sphinx 8.0
        - sphinx>=8.0,<9.0
    - method: pip
      requirements: source/requirements.txt

sphinx:
  configuration: source/conf.py
  fail_on_warning: true

formats:
  - pdf
