version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: source/requirements.txt

sphinx:
  configuration: source/conf.py
  fail_on_warning: true

formats:
  - pdf
